default[:automatic_updates][:on_boot]='false'
default[:automatic_updates][:on_login]='false'
default[:automatic_updates][:on_monday]='No'
default[:automatic_updates][:on_tuesday]='No'
default[:automatic_updates][:on_wednesday]='No'
default[:automatic_updates][:on_thursday]='No'
default[:automatic_updates][:on_friday]='No'
